// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(uic_dosipasFFI)
import uic_dosipasFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_uic_dosipas_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_uic_dosipas_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureUicDosipasInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterTimestamp: FfiConverterRustBuffer {
    typealias SwiftType = Date

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Date {
        let seconds: Int64 = try readInt(&buf)
        let nanoseconds: UInt32 = try readInt(&buf)
        if seconds >= 0 {
            let delta = Double(seconds) + (Double(nanoseconds) / 1.0e9)
            return Date.init(timeIntervalSince1970: delta)
        } else {
            let delta = Double(seconds) - (Double(nanoseconds) / 1.0e9)
            return Date.init(timeIntervalSince1970: delta)
        }
    }

    public static func write(_ value: Date, into buf: inout [UInt8]) {
        var delta = value.timeIntervalSince1970
        var sign: Int64 = 1
        if delta < 0 {
            // The nanoseconds portion of the epoch offset must always be
            // positive, to simplify the calculation we will use the absolute
            // value of the offset.
            sign = -1
            delta = -delta
        }
        if delta.rounded(.down) > Double(Int64.max) {
            fatalError("Timestamp overflow, exceeds max bounds supported by Uniffi")
        }
        let seconds = Int64(delta)
        let nanoseconds = UInt32((delta - Double(seconds)) * 1.0e9)
        writeInt(&buf, sign * seconds)
        writeInt(&buf, nanoseconds)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDuration: FfiConverterRustBuffer {
    typealias SwiftType = TimeInterval

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimeInterval {
        let seconds: UInt64 = try readInt(&buf)
        let nanoseconds: UInt32 = try readInt(&buf)
        return Double(seconds) + (Double(nanoseconds) / 1.0e9)
    }

    public static func write(_ value: TimeInterval, into buf: inout [UInt8]) {
        if value.rounded(.down) > Double(Int64.max) {
            fatalError("Duration overflow, exceeds max bounds supported by Uniffi")
        }

        if value < 0 {
            fatalError("Invalid duration, must be non-negative")
        }

        let seconds = UInt64(value)
        let nanoseconds = UInt32((value - Double(seconds)) * 1.0e9)
        writeInt(&buf, seconds)
        writeInt(&buf, nanoseconds)
    }
}




public protocol DosipasProtocol: AnyObject, Sendable {
    
    func endOfValidity()  -> Date?
    
    func isMatchingPublicKey(key: PublicKey)  -> Bool
    
    func keyId()  -> UInt32
    
    func level2Data()  -> Record?
    
    func records()  -> [Record]
    
    func securityProvider()  -> String
    
    func setDynamicContent(data: DynamicContentData) throws 
    
    func sign(key: PrivateKey) throws  -> Data
    
    func validityDuration()  -> TimeInterval?
    
}
open class Dosipas: DosipasProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uic_dosipas_fn_clone_dosipas(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uic_dosipas_fn_free_dosipas(handle, $0) }
    }

    
public static func newFromBytes(data: Data)throws  -> Dosipas  {
    return try  FfiConverterTypeDosipas_lift(try rustCallWithError(FfiConverterTypeBarcodeError_lift) {
    uniffi_uic_dosipas_fn_constructor_dosipas_new_from_bytes(
        FfiConverterData.lower(data),$0
    )
})
}
    

    
open func endOfValidity() -> Date?  {
    return try!  FfiConverterOptionTimestamp.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_dosipas_end_of_validity(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func isMatchingPublicKey(key: PublicKey) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_dosipas_is_matching_public_key(
            self.uniffiCloneHandle(),
        FfiConverterTypePublicKey_lower(key),$0
    )
})
}
    
open func keyId() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_dosipas_key_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func level2Data() -> Record?  {
    return try!  FfiConverterOptionTypeRecord.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_dosipas_level_2_data(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func records() -> [Record]  {
    return try!  FfiConverterSequenceTypeRecord.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_dosipas_records(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func securityProvider() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_dosipas_security_provider(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func setDynamicContent(data: DynamicContentData)throws   {try rustCallWithError(FfiConverterTypeBarcodeError_lift) {
    uniffi_uic_dosipas_fn_method_dosipas_set_dynamic_content(
            self.uniffiCloneHandle(),
        FfiConverterTypeDynamicContentData_lower(data),$0
    )
}
}
    
open func sign(key: PrivateKey)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeBarcodeError_lift) {
    uniffi_uic_dosipas_fn_method_dosipas_sign(
            self.uniffiCloneHandle(),
        FfiConverterTypePrivateKey_lower(key),$0
    )
})
}
    
open func validityDuration() -> TimeInterval?  {
    return try!  FfiConverterOptionDuration.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_dosipas_validity_duration(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDosipas: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Dosipas

    public static func lift(_ handle: UInt64) throws -> Dosipas {
        return Dosipas(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Dosipas) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Dosipas {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Dosipas, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDosipas_lift(_ handle: UInt64) throws -> Dosipas {
    return try FfiConverterTypeDosipas.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDosipas_lower(_ value: Dosipas) -> UInt64 {
    return FfiConverterTypeDosipas.lower(value)
}






public protocol DynamicContentDataProtocol: AnyObject, Sendable {
    
    func addResponseToChallenge(response: Record) 
    
    func setCoordinate(coordinate: GeoCoordinate) 
    
    func setExtension(response: Record) 
    
    func setMobileAppId(appId: String) throws 
    
    func setTimestamp(time: Date) 
    
}
open class DynamicContentData: DynamicContentDataProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uic_dosipas_fn_clone_dynamiccontentdata(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_uic_dosipas_fn_constructor_dynamiccontentdata_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uic_dosipas_fn_free_dynamiccontentdata(handle, $0) }
    }

    

    
open func addResponseToChallenge(response: Record)  {try! rustCall() {
    uniffi_uic_dosipas_fn_method_dynamiccontentdata_add_response_to_challenge(
            self.uniffiCloneHandle(),
        FfiConverterTypeRecord_lower(response),$0
    )
}
}
    
open func setCoordinate(coordinate: GeoCoordinate)  {try! rustCall() {
    uniffi_uic_dosipas_fn_method_dynamiccontentdata_set_coordinate(
            self.uniffiCloneHandle(),
        FfiConverterTypeGeoCoordinate_lower(coordinate),$0
    )
}
}
    
open func setExtension(response: Record)  {try! rustCall() {
    uniffi_uic_dosipas_fn_method_dynamiccontentdata_set_extension(
            self.uniffiCloneHandle(),
        FfiConverterTypeRecord_lower(response),$0
    )
}
}
    
open func setMobileAppId(appId: String)throws   {try rustCallWithError(FfiConverterTypeBarcodeError_lift) {
    uniffi_uic_dosipas_fn_method_dynamiccontentdata_set_mobile_app_id(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(appId),$0
    )
}
}
    
open func setTimestamp(time: Date)  {try! rustCall() {
    uniffi_uic_dosipas_fn_method_dynamiccontentdata_set_timestamp(
            self.uniffiCloneHandle(),
        FfiConverterTimestamp.lower(time),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDynamicContentData: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = DynamicContentData

    public static func lift(_ handle: UInt64) throws -> DynamicContentData {
        return DynamicContentData(unsafeFromHandle: handle)
    }

    public static func lower(_ value: DynamicContentData) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DynamicContentData {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: DynamicContentData, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDynamicContentData_lift(_ handle: UInt64) throws -> DynamicContentData {
    return try FfiConverterTypeDynamicContentData.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDynamicContentData_lower(_ value: DynamicContentData) -> UInt64 {
    return FfiConverterTypeDynamicContentData.lower(value)
}






public protocol GeoCoordinateProtocol: AnyObject, Sendable {
    
    func setAccuracyFromMeters(accuracy: Double) 
    
    func setAccuracyRaw(accuracy: GeoUnit) 
    
    func setCoordinateSystem(system: GeoCoordinateSystem) 
    
}
open class GeoCoordinate: GeoCoordinateProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uic_dosipas_fn_clone_geocoordinate(self.handle, $0) }
    }
public convenience init(position: LatLong) {
    let handle =
        try! rustCall() {
    uniffi_uic_dosipas_fn_constructor_geocoordinate_new(
        FfiConverterTypeLatLong_lower(position),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uic_dosipas_fn_free_geocoordinate(handle, $0) }
    }

    

    
open func setAccuracyFromMeters(accuracy: Double)  {try! rustCall() {
    uniffi_uic_dosipas_fn_method_geocoordinate_set_accuracy_from_meters(
            self.uniffiCloneHandle(),
        FfiConverterDouble.lower(accuracy),$0
    )
}
}
    
open func setAccuracyRaw(accuracy: GeoUnit)  {try! rustCall() {
    uniffi_uic_dosipas_fn_method_geocoordinate_set_accuracy_raw(
            self.uniffiCloneHandle(),
        FfiConverterTypeGeoUnit_lower(accuracy),$0
    )
}
}
    
open func setCoordinateSystem(system: GeoCoordinateSystem)  {try! rustCall() {
    uniffi_uic_dosipas_fn_method_geocoordinate_set_coordinate_system(
            self.uniffiCloneHandle(),
        FfiConverterTypeGeoCoordinateSystem_lower(system),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGeoCoordinate: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = GeoCoordinate

    public static func lift(_ handle: UInt64) throws -> GeoCoordinate {
        return GeoCoordinate(unsafeFromHandle: handle)
    }

    public static func lower(_ value: GeoCoordinate) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GeoCoordinate {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: GeoCoordinate, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeoCoordinate_lift(_ handle: UInt64) throws -> GeoCoordinate {
    return try FfiConverterTypeGeoCoordinate.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeoCoordinate_lower(_ value: GeoCoordinate) -> UInt64 {
    return FfiConverterTypeGeoCoordinate.lower(value)
}






public protocol Keychain: AnyObject, Sendable {
    
    func genP256Key()  -> KeychainKey
    
    func getByKeyId(keyId: String)  -> KeychainKey?
    
}
open class KeychainImpl: Keychain, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uic_dosipas_fn_clone_keychain(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uic_dosipas_fn_free_keychain(handle, $0) }
    }

    

    
open func genP256Key() -> KeychainKey  {
    return try!  FfiConverterTypeKeychainKey_lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_keychain_gen_p256_key(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getByKeyId(keyId: String) -> KeychainKey?  {
    return try!  FfiConverterOptionTypeKeychainKey.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_keychain_get_by_key_id(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(keyId),$0
    )
})
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceKeychain {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceKeychain = UniffiVTableCallbackInterfaceKeychain(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeKeychain.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface Keychain: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeKeychain.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface Keychain: handle missing in uniffiClone")
            }
        },
        genP256Key: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<UInt64>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> KeychainKey in
                guard let uniffiObj = try? FfiConverterTypeKeychain.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.genP256Key(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterTypeKeychainKey_lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        getByKeyId: { (
            uniffiHandle: UInt64,
            keyId: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> KeychainKey? in
                guard let uniffiObj = try? FfiConverterTypeKeychain.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.getByKeyId(
                     keyId: try FfiConverterString.lift(keyId)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterOptionTypeKeychainKey.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceKeychain> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceKeychain>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitKeychain() {
    uniffi_uic_dosipas_fn_init_callback_vtable_keychain(UniffiCallbackInterfaceKeychain.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeychain: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<Keychain>()

    typealias FfiType = UInt64
    typealias SwiftType = Keychain

    public static func lift(_ handle: UInt64) throws -> Keychain {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return KeychainImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: Keychain) -> UInt64 {
         if let rustImpl = value as? KeychainImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Keychain {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Keychain, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeychain_lift(_ handle: UInt64) throws -> Keychain {
    return try FfiConverterTypeKeychain.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeychain_lower(_ value: Keychain) -> UInt64 {
    return FfiConverterTypeKeychain.lower(value)
}






public protocol KeychainKey: AnyObject, Sendable {
    
    func keyId()  -> String
    
    func publicKey()  -> Data
    
    func sign(message: Data)  -> Data
    
    func variant()  -> KeyVariant
    
}
open class KeychainKeyImpl: KeychainKey, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uic_dosipas_fn_clone_keychainkey(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uic_dosipas_fn_free_keychainkey(handle, $0) }
    }

    

    
open func keyId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_keychainkey_key_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func publicKey() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_keychainkey_public_key(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func sign(message: Data) -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_keychainkey_sign(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(message),$0
    )
})
}
    
open func variant() -> KeyVariant  {
    return try!  FfiConverterTypeKeyVariant_lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_keychainkey_variant(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceKeychainKey {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceKeychainKey = UniffiVTableCallbackInterfaceKeychainKey(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeKeychainKey.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface KeychainKey: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeKeychainKey.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface KeychainKey: handle missing in uniffiClone")
            }
        },
        keyId: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterTypeKeychainKey.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.keyId(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        publicKey: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data in
                guard let uniffiObj = try? FfiConverterTypeKeychainKey.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.publicKey(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterData.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        sign: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data in
                guard let uniffiObj = try? FfiConverterTypeKeychainKey.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.sign(
                     message: try FfiConverterData.lift(message)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterData.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        variant: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> KeyVariant in
                guard let uniffiObj = try? FfiConverterTypeKeychainKey.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.variant(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterTypeKeyVariant_lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceKeychainKey> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceKeychainKey>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitKeychainKey() {
    uniffi_uic_dosipas_fn_init_callback_vtable_keychainkey(UniffiCallbackInterfaceKeychainKey.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeychainKey: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<KeychainKey>()

    typealias FfiType = UInt64
    typealias SwiftType = KeychainKey

    public static func lift(_ handle: UInt64) throws -> KeychainKey {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return KeychainKeyImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: KeychainKey) -> UInt64 {
         if let rustImpl = value as? KeychainKeyImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeychainKey {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: KeychainKey, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeychainKey_lift(_ handle: UInt64) throws -> KeychainKey {
    return try FfiConverterTypeKeychainKey.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeychainKey_lower(_ value: KeychainKey) -> UInt64 {
    return FfiConverterTypeKeychainKey.lower(value)
}






public protocol PrivateKeyProtocol: AnyObject, Sendable {
    
    func keyId()  -> String
    
    func publicKey()  -> PublicKey
    
}
open class PrivateKey: PrivateKeyProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uic_dosipas_fn_clone_privatekey(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uic_dosipas_fn_free_privatekey(handle, $0) }
    }

    
public static func fromKeychain(keychain: Keychain, keyId: String)throws  -> PrivateKey  {
    return try  FfiConverterTypePrivateKey_lift(try rustCallWithError(FfiConverterTypeBarcodeError_lift) {
    uniffi_uic_dosipas_fn_constructor_privatekey_from_keychain(
        FfiConverterTypeKeychain_lower(keychain),
        FfiConverterString.lower(keyId),$0
    )
})
}
    
public static func genP256(keychain: Keychain) -> PrivateKey  {
    return try!  FfiConverterTypePrivateKey_lift(try! rustCall() {
    uniffi_uic_dosipas_fn_constructor_privatekey_gen_p256(
        FfiConverterTypeKeychain_lower(keychain),$0
    )
})
}
    

    
open func keyId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_privatekey_key_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func publicKey() -> PublicKey  {
    return try!  FfiConverterTypePublicKey_lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_privatekey_public_key(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrivateKey: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PrivateKey

    public static func lift(_ handle: UInt64) throws -> PrivateKey {
        return PrivateKey(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PrivateKey) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivateKey {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PrivateKey, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKey_lift(_ handle: UInt64) throws -> PrivateKey {
    return try FfiConverterTypePrivateKey.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKey_lower(_ value: PrivateKey) -> UInt64 {
    return FfiConverterTypePrivateKey.lower(value)
}






public protocol PublicKeyProtocol: AnyObject, Sendable {
    
    func eqPrivateKey(priv: PrivateKey)  -> Bool
    
    func keyAlgList()  -> [UInt32]
    
    func keyAlgStr()  -> String
    
    func publicBytes()  -> Data
    
    func signingAlgList()  -> [UInt32]
    
    func signingAlgStr()  -> String
    
}
open class PublicKey: PublicKeyProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_uic_dosipas_fn_clone_publickey(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_uic_dosipas_fn_free_publickey(handle, $0) }
    }

    

    
open func eqPrivateKey(priv: PrivateKey) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_publickey_eq_private_key(
            self.uniffiCloneHandle(),
        FfiConverterTypePrivateKey_lower(priv),$0
    )
})
}
    
open func keyAlgList() -> [UInt32]  {
    return try!  FfiConverterSequenceUInt32.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_publickey_key_alg_list(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func keyAlgStr() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_publickey_key_alg_str(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func publicBytes() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_publickey_public_bytes(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func signingAlgList() -> [UInt32]  {
    return try!  FfiConverterSequenceUInt32.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_publickey_signing_alg_list(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func signingAlgStr() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_uic_dosipas_fn_method_publickey_signing_alg_str(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePublicKey: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PublicKey

    public static func lift(_ handle: UInt64) throws -> PublicKey {
        return PublicKey(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PublicKey) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PublicKey {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PublicKey, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePublicKey_lift(_ handle: UInt64) throws -> PublicKey {
    return try FfiConverterTypePublicKey.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePublicKey_lower(_ value: PublicKey) -> UInt64 {
    return FfiConverterTypePublicKey.lower(value)
}




public struct LatLong: Equatable, Hashable, Codable {
    public var latitude: Double
    public var longitude: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(latitude: Double, longitude: Double) {
        self.latitude = latitude
        self.longitude = longitude
    }

    

    
}

#if compiler(>=6)
extension LatLong: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLatLong: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LatLong {
        return
            try LatLong(
                latitude: FfiConverterDouble.read(from: &buf), 
                longitude: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: LatLong, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.latitude, into: &buf)
        FfiConverterDouble.write(value.longitude, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLatLong_lift(_ buf: RustBuffer) throws -> LatLong {
    return try FfiConverterTypeLatLong.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLatLong_lower(_ value: LatLong) -> RustBuffer {
    return FfiConverterTypeLatLong.lower(value)
}


public struct Record: Equatable, Hashable, Codable {
    public var recordId: String
    public var data: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(recordId: String, data: Data) {
        self.recordId = recordId
        self.data = data
    }

    

    
}

#if compiler(>=6)
extension Record: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Record {
        return
            try Record(
                recordId: FfiConverterString.read(from: &buf), 
                data: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: Record, into buf: inout [UInt8]) {
        FfiConverterString.write(value.recordId, into: &buf)
        FfiConverterData.write(value.data, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecord_lift(_ buf: RustBuffer) throws -> Record {
    return try FfiConverterTypeRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecord_lower(_ value: Record) -> RustBuffer {
    return FfiConverterTypeRecord.lower(value)
}


public enum BarcodeError: Swift.Error, Equatable, Hashable, Codable, Foundation.LocalizedError {

    
    
    case UnknownBarcodeType
    case InvalidFormat(msg: String
    )
    case CryptographyError(msg: String
    )
    case UnsupportedData(msg: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension BarcodeError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBarcodeError: FfiConverterRustBuffer {
    typealias SwiftType = BarcodeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BarcodeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .UnknownBarcodeType
        case 2: return .InvalidFormat(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .CryptographyError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .UnsupportedData(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BarcodeError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .UnknownBarcodeType:
            writeInt(&buf, Int32(1))
        
        
        case let .InvalidFormat(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .CryptographyError(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .UnsupportedData(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBarcodeError_lift(_ buf: RustBuffer) throws -> BarcodeError {
    return try FfiConverterTypeBarcodeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBarcodeError_lower(_ value: BarcodeError) -> RustBuffer {
    return FfiConverterTypeBarcodeError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum GeoCoordinateSystem: Equatable, Hashable, Codable {
    
    case wgs84
    case grs80





}

#if compiler(>=6)
extension GeoCoordinateSystem: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGeoCoordinateSystem: FfiConverterRustBuffer {
    typealias SwiftType = GeoCoordinateSystem

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GeoCoordinateSystem {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .wgs84
        
        case 2: return .grs80
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: GeoCoordinateSystem, into buf: inout [UInt8]) {
        switch value {
        
        
        case .wgs84:
            writeInt(&buf, Int32(1))
        
        
        case .grs80:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeoCoordinateSystem_lift(_ buf: RustBuffer) throws -> GeoCoordinateSystem {
    return try FfiConverterTypeGeoCoordinateSystem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeoCoordinateSystem_lower(_ value: GeoCoordinateSystem) -> RustBuffer {
    return FfiConverterTypeGeoCoordinateSystem.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum GeoUnit: Equatable, Hashable, Codable {
    
    case microDegree
    case tenthMilliDegree
    case milliDegree
    case centiDegree
    case deciDegree





}

#if compiler(>=6)
extension GeoUnit: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGeoUnit: FfiConverterRustBuffer {
    typealias SwiftType = GeoUnit

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GeoUnit {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .microDegree
        
        case 2: return .tenthMilliDegree
        
        case 3: return .milliDegree
        
        case 4: return .centiDegree
        
        case 5: return .deciDegree
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: GeoUnit, into buf: inout [UInt8]) {
        switch value {
        
        
        case .microDegree:
            writeInt(&buf, Int32(1))
        
        
        case .tenthMilliDegree:
            writeInt(&buf, Int32(2))
        
        
        case .milliDegree:
            writeInt(&buf, Int32(3))
        
        
        case .centiDegree:
            writeInt(&buf, Int32(4))
        
        
        case .deciDegree:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeoUnit_lift(_ buf: RustBuffer) throws -> GeoUnit {
    return try FfiConverterTypeGeoUnit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeoUnit_lower(_ value: GeoUnit) -> RustBuffer {
    return FfiConverterTypeGeoUnit.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum KeyVariant: Equatable, Hashable, Codable {
    
    case p256





}

#if compiler(>=6)
extension KeyVariant: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeyVariant: FfiConverterRustBuffer {
    typealias SwiftType = KeyVariant

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeyVariant {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .p256
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: KeyVariant, into buf: inout [UInt8]) {
        switch value {
        
        
        case .p256:
            writeInt(&buf, Int32(1))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyVariant_lift(_ buf: RustBuffer) throws -> KeyVariant {
    return try FfiConverterTypeKeyVariant.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyVariant_lower(_ value: KeyVariant) -> RustBuffer {
    return FfiConverterTypeKeyVariant.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTimestamp: FfiConverterRustBuffer {
    typealias SwiftType = Date?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTimestamp.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTimestamp.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDuration: FfiConverterRustBuffer {
    typealias SwiftType = TimeInterval?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDuration.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDuration.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeKeychainKey: FfiConverterRustBuffer {
    typealias SwiftType = KeychainKey?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeKeychainKey.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeKeychainKey.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRecord: FfiConverterRustBuffer {
    typealias SwiftType = Record?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRecord: FfiConverterRustBuffer {
    typealias SwiftType = [Record]

    public static func write(_ value: [Record], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Record] {
        let len: Int32 = try readInt(&buf)
        var seq = [Record]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRecord.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_uic_dosipas_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dosipas_end_of_validity() != 13536) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dosipas_is_matching_public_key() != 14857) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dosipas_key_id() != 1397) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dosipas_level_2_data() != 56126) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dosipas_records() != 1557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dosipas_security_provider() != 21432) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dosipas_set_dynamic_content() != 19350) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dosipas_sign() != 50656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dosipas_validity_duration() != 63426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dynamiccontentdata_add_response_to_challenge() != 2531) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dynamiccontentdata_set_coordinate() != 62579) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dynamiccontentdata_set_extension() != 11274) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dynamiccontentdata_set_mobile_app_id() != 42372) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_dynamiccontentdata_set_timestamp() != 46174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_geocoordinate_set_accuracy_from_meters() != 27039) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_geocoordinate_set_accuracy_raw() != 13471) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_geocoordinate_set_coordinate_system() != 31678) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_keychain_gen_p256_key() != 5341) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_keychain_get_by_key_id() != 14958) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_keychainkey_key_id() != 17975) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_keychainkey_public_key() != 56922) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_keychainkey_sign() != 59117) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_keychainkey_variant() != 47429) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_privatekey_key_id() != 30842) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_privatekey_public_key() != 24974) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_publickey_eq_private_key() != 35059) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_publickey_key_alg_list() != 23598) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_publickey_key_alg_str() != 63330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_publickey_public_bytes() != 32494) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_publickey_signing_alg_list() != 51183) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_method_publickey_signing_alg_str() != 22153) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_constructor_dosipas_new_from_bytes() != 62370) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_constructor_dynamiccontentdata_new() != 65496) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_constructor_geocoordinate_new() != 40772) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_constructor_privatekey_from_keychain() != 42027) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_uic_dosipas_checksum_constructor_privatekey_gen_p256() != 13840) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitKeychain()
    uniffiCallbackInitKeychainKey()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureUicDosipasInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all